services:
  - type: web
    name: mailtraceai-api
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.3
      - key: ALLOWED_ORIGINS
        sync: false
      - key: VIRUSTOTAL_API_KEY
        sync: false
      - key: ABUSEIPDB_API_KEY
        sync: false
